package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * ExamesRepositorio generated by hbm2java
 */
@Entity
@Table(name="exames"
    ,catalog="consultar"
)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idexames")

public class Exames  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "exames_id_seq")
    @SequenceGenerator(
            name = "exames_id_seq",
            sequenceName = "exames_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer idexames;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "descricao")
     private String descricao;
    @NotNull
    @Column(name = "horario")
     private String horario;
    @NotNull
    @Column(name = "valor")
     private Short valor;
    @NotNull
    @Column(name = "status")
     private Integer status;


//    @ManyToMany(mappedBy = "exames", fetch = FetchType.LAZY,cascade = CascadeType.ALL)
//    //@JsonManagedReference(value = "unidadeDeSaude")
//    private List<UnidadeDeSaude> unidadeDeSaude;

//    public Exames(String nome, String descricao, String horario, Short valor, Integer status) {
//       this.setNome(nome);
//       this.setDescricao(descricao);
//       this.setHorario(horario);
//       this.setValor(valor);
//       this.setStatus(status);
//    }


    public Integer getIdexames() {
        return idexames;
    }

    public void setIdexames(Integer idexames) {
        this.idexames = idexames;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getHorario() {
        return horario;
    }

    public void setHorario(String horario) {
        this.horario = horario;
    }

    public Short getValor() {
        return valor;
    }

    public void setValor(Short valor) {
        this.valor = valor;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

//
}


