package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * ImagemRepositorio generated by hbm2java
 */
@Entity
@Table(name="imagem"
    ,catalog="consultar"
)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idimagem")

public class Imagem  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "imagem_id_seq")
    @SequenceGenerator(
            name = "imagem_id_seq",
            sequenceName = "imagem_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer idimagem;
    @NotNull
    @Column(name = "url")
     private String url;
    @NotNull
    @Column(name = "link")
     private String link;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "status")
     private Integer status;

   
//
//    public Imagem(String url, String link, String nome, Integer status) {
//       this.setUrl(url);
//       this.setLink(link);
//       this.setNome(nome);
//       this.setStatus(status);
//    }


    public Integer getIdimagem() {
        return idimagem;
    }

    public void setIdimagem(Integer idimagem) {
        this.idimagem = idimagem;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}


