package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * SetorRepositorio generated by hbm2java
 */
@Entity
@Table(name="setor"
    ,catalog="consultar"
)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idsetor")

public class Setor  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "setor_id_seq")
    @SequenceGenerator(
            name = "setor_id_seq",
            sequenceName = "setor_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer idsetor;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "descricao")
     private String descricao;
    @NotNull
    @Column(name = "status")
     private Integer status;

//    @OneToMany(mappedBy = "setor", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
//    private List<Contato> contato;

//    public Setor(String nome, String descricao, String status, List<Contato> contato) {
//        this.setNome(nome);
//        this.setDescricao(descricao);
//        this.setStatus(status);
//        this.setContato(contato);
//    }


    public Integer getIdsetor() {
        return idsetor;
    }

    public void setIdsetor(Integer idsetor) {
        this.idsetor = idsetor;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

//    public List<Contato> getContato() {
//        return contato;
//    }
//
//    public void setContato(List<Contato> contato) {
//        this.contato = contato;
//    }
}


