package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.List;

/**
 * AcessoRepositorio generated by hbm2java
 */
@Entity
@Table(name="acesso")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idacesso")

public class Acesso  implements Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "acesso_id_seq")
    @SequenceGenerator(
            name = "acesso_id_seq",
            sequenceName = "acesso_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")
     private Integer idacesso;
    @NotNull
    @Column(name = "email")
     private String email;
    @NotNull
    @Column(name = "senha")
     private String senha;

    @ManyToMany
    @JoinTable(name = "acesso_permissoes",
            joinColumns=@JoinColumn(name = "acesso_id"),
            inverseJoinColumns=@JoinColumn(name = "permissao_id"))
    //@JsonManagedReference(value = "pessoa_permissões")
    private List<Permissao> permissoes;





    public Integer getIdacesso() {
        return idacesso;
    }

    public void setIdacesso(Integer idacesso) {
        this.idacesso = idacesso;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public List<Permissao> getPermissoes() {
        return permissoes;
    }

    public void setPermissoes(List<Permissao> permissoes) {
        this.permissoes = permissoes;
    }
}


