package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * CidadeRepositorio generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="consultar"
)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idcidade")

public class Cidade  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "cidade_id_seq")
    @SequenceGenerator(
            name = "cidade_id_seq",
            sequenceName = "cidade_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer idcidade;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "status")
     private Integer status;


    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="estado_id")
    private Estado estado;

//    public Cidade(String nome, Integer status, List<Bairro> bairro, Estado estado) {
//        this.setNome(nome);
//        this.setStatus(status);
//        this.setBairro(bairro);
//        this.setEstado(estado);
//    }


    public Integer getIdcidade() {
        return idcidade;
    }

    public void setIdcidade(Integer idcidade) {
        this.idcidade = idcidade;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }



    public Estado getEstado() {
        return estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }
}


