package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * DadosClinicoRepositorio generated by hbm2java
 */
@Entity
@Table(name="dados_clinico"
    ,catalog="consultar"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "iddadosClinico")

public class DadosClinico  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "dados_clinico_id_seq")
    @SequenceGenerator(
            name = "dados_clinico_id_seq",
            sequenceName = "dados_clinico_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer iddadosClinico;
    @NotNull
    @Column(name = "tipo_sanguineo")
     private String tipoSanguineo;
    @NotNull
    @Column(name = "fator_rh")
     private String fatorRh;
    @NotNull
    @Column(name = "medicamento")
     private String medicamento;
    @NotNull
    @Column(name = "doenca")
     private String doenca;
    @NotNull
    @Column(name = "doenca_familiar")
     private String doencaFamiliar;
    @NotNull
    @Column(name = "alergiaMedicamento")
     private String alergiaMedicamento;

//    public DadosClinico(String tipoSanguineo, String fatorRh, String medicamento, String doenca, String doencaFamiliar, String alergiaMedicamento) {
//        this.setTipoSanguineo(tipoSanguineo);
//        this.setFatorRh(fatorRh);
//        this.setMedicamento(medicamento);
//        this.setDoenca(doenca);
//        this.setDoencaFamiliar(doencaFamiliar);
//        this.setAlergiaMedicamento(alergiaMedicamento);
//    }


    public Integer getIddadosClinico() {
        return iddadosClinico;
    }

    public void setIddadosClinico(Integer iddadosClinico) {
        this.iddadosClinico = iddadosClinico;
    }

    public String getTipoSanguineo() {
        return tipoSanguineo;
    }

    public void setTipoSanguineo(String tipoSanguineo) {
        this.tipoSanguineo = tipoSanguineo;
    }

    public String getFatorRh() {
        return fatorRh;
    }

    public void setFatorRh(String fatorRh) {
        this.fatorRh = fatorRh;
    }

    public String getMedicamento() {
        return medicamento;
    }

    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }

    public String getDoenca() {
        return doenca;
    }

    public void setDoenca(String doenca) {
        this.doenca = doenca;
    }

    public String getDoencaFamiliar() {
        return doencaFamiliar;
    }

    public void setDoencaFamiliar(String doencaFamiliar) {
        this.doencaFamiliar = doencaFamiliar;
    }

    public String getAlergiaMedicamento() {
        return alergiaMedicamento;
    }

    public void setAlergiaMedicamento(String alergiaMedicamento) {
        this.alergiaMedicamento = alergiaMedicamento;
    }
}


