package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * FeedNoticiasRepositorio generated by hbm2java
 */
@Entity
@Table(name="feed_noticias"
    ,catalog="consultar"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idfeedNoticias" +
        "")

public class FeedNoticias  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "feed_noticia_id_seq")
    @SequenceGenerator(
            name = "feed_noticia_id_seq",
            sequenceName = "feed_noticia_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Long idfeedNoticias;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "descricao")
     private String descricao;
    @NotNull
    @Column(name = "tipo")
     private Integer tipo;
    @NotNull
    @Column(name = "status")
     private Integer status;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="imagem_id")
    private Imagem imagem;


    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="usuario_id")
    private Usuario usuario;

//
//    public FeedNoticias(String nome, String descricao, Integer tipo, Integer status, Imagem imagem, Usuario usuario) {
//        this.setNome(nome);
//        this.setDescricao(descricao);
//        this.setTipo(tipo);
//        this.setStatus(status);
//        this.setImagem(imagem);
//        this.setUsuario(usuario);
//    }


    @Override
    public String toString() {
        return "FeedNoticias{" +
                "idfeedNoticias=" + idfeedNoticias +
                ", nome='" + nome + '\'' +
                ", descricao='" + descricao + '\'' +
                ", tipo=" + tipo +
                ", status=" + status +
                ", imagem=" + imagem +
                ", usuario=" + usuario +
                '}';
    }

    public Long getIdfeedNoticias() {
        return idfeedNoticias;
    }

    public void setIdfeedNoticias(Long idfeedNoticias) {
        this.idfeedNoticias = idfeedNoticias;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Integer getTipo() {
        return tipo;
    }

    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Imagem getImagem() {
        return imagem;
    }

    public void setImagem(Imagem imagem) {
        this.imagem = imagem;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}



