package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * LeitoRepositorio generated by hbm2java
 */
@Entity
@Table(name="leito"
    ,catalog="consultar"
)
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idleito")

public class Leito  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "leito_id_seq")
    @SequenceGenerator(
            name = "leito_id_seq",
            sequenceName = "leito_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer idleito;
    @NotNull
    @Column(name = "tipo")
     private int tipo;
    @NotNull
    @Column(name = "descricao")
     private String descricao;
    @NotNull
    @Column(name = "status")
     private Integer status;

//
//    @ManyToOne(cascade = CascadeType.ALL)
//    @JoinColumn(name = "unidade_de_saude_id")
//     private UnidadeDeSaude unidadeDeSaude;

//    public Leito(int tipo, String descricao, String status, UnidadeDeSaude unidadeDeSaude) {
//        this.setTipo(tipo);
//        this.setDescricao(descricao);
//        this.setStatus(status);
//        this.setUnidadeDeSaude(unidadeDeSaude);
//    }


    public Integer getIdleito() {
        return idleito;
    }

    public void setIdleito(Integer idleito) {
        this.idleito = idleito;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

//    public UnidadeDeSaude getUnidadeDeSaude() {
//        return unidadeDeSaude;
//    }
//
//    public void setUnidadeDeSaude(UnidadeDeSaude unidadeDeSaude) {
//        this.unidadeDeSaude = unidadeDeSaude;
//    }
}


