package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * AcessoRepositorio generated by hbm2java
 */
@Entity
@Table(name="medicamento"
    ,catalog="consultar"
)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")

public class Medicamento implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "medicamento_id_seq")
    @SequenceGenerator(
            name = "medicamento_id_seq",
            sequenceName = "medicamento_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")
     private Integer id;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "descricao")
     private String descricao;

    @NotNull
    @Column(name = "status")
    private Integer status;

//    @OneToMany(mappedBy = "medicamento",  fetch = FetchType.EAGER, cascade = CascadeType.ALL)
//    private List<UnidadeDeSaude> unidadeDeSaude;
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

//    public List<UnidadeDeSaude> getUnidadeDeSaude() {
//        return unidadeDeSaude;
//    }

//    public void setUnidadeDeSaude(List<UnidadeDeSaude> unidadeDeSaude) {
//        this.unidadeDeSaude = unidadeDeSaude;
//    }
}


