package com.consultar.entidade;
// Generated 31/03/2017 19:48:10 by Hibernate Tools 4.3.1


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * RuaRepositorio generated by hbm2java
 */
@Entity
@Table(name="rua"
    ,catalog="consultar"
)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "idrua")

public class Rua  implements java.io.Serializable {

    @Id
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "rua_id_seq")
    @SequenceGenerator(
            name = "rua_id_seq",
            sequenceName = "rua_id_seq",
            allocationSize = 1)//de quanto em quanto ele incrementa

    @Column(name = "id")

     private Integer idrua;
    @NotNull
    @Column(name = "nome")
     private String nome;
    @NotNull
    @Column(name = "status")
     private Integer status;



//    @OneToOne(mappedBy = "rua", fetch = FetchType.LAZY)
//    private Endereco endereco;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "bairro_id")
    private Bairro bairro;

    public Bairro getBairro() {
        return bairro;
    }

    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }

//    public Endereco getEndereco() {
//        return endereco;
//    }
//
//    public void setEndereco(Endereco endereco) {
//        this.endereco = endereco;
//    }
//


    public Integer getIdrua() {
        return idrua;
    }

    public void setIdrua(Integer idrua) {
        this.idrua = idrua;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}


